DROP DATABASE IF EXISTS HibernateExample;

CREATE DATABASE HibernateExample;

USE HibernateExample;

CREATE TABLE SHOWROOM_LIST2 (
SHOWROOM_ID int(10) NOT NULL AUTO_INCREMENT,
manager varchar(255) DEFAULT NULL,
PRIMARY KEY (SHOWROOM_ID)
);

CREATE TABLE CAR_LIST2 (
CAR_ID int(11) NOT NULL AUTO_INCREMENT,
color varchar(255) DEFAULT NULL,
name varchar(255) DEFAULT NULL,
PRIMARY KEY (CAR_ID)
);

CREATE TABLE SHOWROOM_SET_JOINTABLE (
SHOWROOM_ID int(11) NOT NULL,
CAR_ID int(11) NOT NULL,
PRIMARY KEY (SHOWROOM_ID,CAR_ID),
FOREIGN KEY (SHOWROOM_ID) REFERENCES SHOWROOM_LIST2 (SHOWROOM_ID),
FOREIGN KEY (CAR_ID) REFERENCES CAR_LIST2 (CAR_ID)
);